### ISSUE TITLE
`prisma generate` throw Error:  `Expected property name or '}' in JSON at position 29`

### ISSUE THREAD

**Issue by TenviLi** [fdarian/prisma-generator-drizzle#38]
I followed the instructions in the README and executed the relevant commands. 

However, when I reached the following command, an error occurred. 

I searched extensively on search engines but couldn't find a solution.

![image](https://github.com/farreldarian/prisma-generator-drizzle/assets/30214981/d4ad8de7-36ab-4d19-9a16-0c2c8d81611f)

```prisma
generator client {
  provider = "prisma-generator-drizzle"
}

datasource db {
  provider = "sqlite"
  url      = "file:../prisma.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

```log
prisma:engines binaries to download libquery-engine, schema-engine +156ms
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +4ms
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +0ms
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +0ms
prisma:get-platform The parsed libssl version is: 3.0.x +0ms
prisma:loadEnv project root found at /home/work/package.json +246ms
prisma:tryLoadEnv Environment variables loaded from /home/work/.env +5ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma:getConfig Using getConfig Wasm +3ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +7ms
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +1ms
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +0ms
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +1ms
prisma:get-platform The parsed libssl version is: 3.0.x +0ms
prisma:getConfig Using getConfig Wasm +34ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +1ms
prisma:getDMMF Using getDmmf Wasm +0ms
prisma:getDMMF Using given datamodel +0ms
prisma:getDMMF dmmf data retrieved without errors in getDmmf Wasm +36ms
prisma:getGenerators neededVersions {} +294ms
Error: Error: 
Expected property name or '}' in JSON at position 29


    at Mf.parse (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1413:71)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Rgt (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1892:280)
```

**Comment by farreldarian** [comment]
> I followed the instructions in the README and executed the relevant commands.
> 
> However, when I reached the following command, an error occurred.
> 
> I searched extensively on search engines but couldn't find a solution.
> 
> ![image](https://private-user-images.githubusercontent.com/30214981/312913222-d4ad8de7-36ab-4d19-9a16-0c2c8d81611f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NTM5NDUsIm5iZiI6MTcxMDQ1MzY0NSwicGF0aCI6Ii8zMDIxNDk4MS8zMTI5MTMyMjItZDRhZDhkZTctMzZhYi00ZDE5LTlhMTYtMGMyYzhkODE2MTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIyMDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOGEwZmY1NTBmMDM3OTIwMGJkMDAzODAzMWVhN2M3OTUyYzM2MjMzNTU4YzMwOTBmYTE0NjZmM2VmNTA2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cjcOxRPiQb0pF1RLmyIThzh0dULvoZeCOsquD1Odgj4)
> 
> ```prisma
> generator client {
>   provider = "prisma-generator-drizzle"
> }
> 
> datasource db {
>   provider = "sqlite"
>   url      = "file:../prisma.db"
> }
> 
> model User {
>   id    Int     @id @default(autoincrement())
>   email String  @unique
>   name  String?
> }
> ```
> 
> ```
> prisma:engines binaries to download libquery-engine, schema-engine +156ms
> prisma:get-platform Found distro info:
> {
>   "targetDistro": "debian",
>   "familyDistro": "debian",
>   "originalDistro": "ubuntu"
> } +4ms
> prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +0ms
> prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +0ms
> prisma:get-platform The parsed libssl version is: 3.0.x +0ms
> prisma:loadEnv project root found at /home/work/package.json +246ms
> prisma:tryLoadEnv Environment variables loaded from /home/work/.env +5ms
> Environment variables loaded from .env
> Prisma schema loaded from prisma/schema.prisma
> prisma:getConfig Using getConfig Wasm +3ms
> prisma:getConfig config data retrieved without errors in getConfig Wasm +7ms
> prisma:get-platform Found distro info:
> {
>   "targetDistro": "debian",
>   "familyDistro": "debian",
>   "originalDistro": "ubuntu"
> } +1ms
> prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +0ms
> prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +1ms
> prisma:get-platform The parsed libssl version is: 3.0.x +0ms
> prisma:getConfig Using getConfig Wasm +34ms
> prisma:getConfig config data retrieved without errors in getConfig Wasm +1ms
> prisma:getDMMF Using getDmmf Wasm +0ms
> prisma:getDMMF Using given datamodel +0ms
> prisma:getDMMF dmmf data retrieved without errors in getDmmf Wasm +36ms
> prisma:getGenerators neededVersions {} +294ms
> Error: Error: 
> Expected property name or '}' in JSON at position 29
> 
> 
>     at Mf.parse (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1413:71)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Rgt (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1892:280)
> ```

Hey, at first glance, it looks like it comes from the Prisma engine. You can try removing the prisma-generator-drizzle plugin and see if the problem persists.

**Comment by TenviLi** [comment]
> > prisma:getGenerators neededVersions {} +294ms
> > Error: Error:
> > Expected property name or '}' in JSON at position 29
> > ```
> > at Mf.parse (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1413:71)
> > ```
> 
> Hey, at first glance, it looks like it comes from the Prisma engine. You can try removing the prisma-generator-drizzle plugin and see if the problem persists.

```prisma
generator client {
  provider = "prisma-client-js"
}
```

no problem

![image](https://github.com/farreldarian/prisma-generator-drizzle/assets/30214981/da3c5960-e7b6-4519-b84d-dbf09dfe7b4a)

**Comment by TenviLi** [comment]
> > prisma:getGenerators neededVersions {} +294ms
> > Error: Error:
> > Expected property name or '}' in JSON at position 29
> > ```
> > at Mf.parse (/home/work/node_modules/.pnpm/prisma@5.10.2/node_modules/prisma/build/index.js:1413:71)
> > ```
> 
> Hey, at first glance, it looks like it comes from the Prisma engine. You can try removing the prisma-generator-drizzle plugin and see if the problem persists.

```prisma
generator client {
  provider = "prisma-client-js"
}
```

no problem
![image](https://github.com/farreldarian/prisma-generator-drizzle/assets/30214981/b50a4b7a-b69e-4600-8837-4c3d6895d634)

**Comment by farreldarian** [comment]
Do you mind sending me a reproduction repo so I can take a better look?

**Comment by farreldarian** [comment]
@TenviLi this might be unrelated, could you also try using bun 1.0.30?

To install a specific version of bun, follow [this step](https://bun.sh/docs/installation#uninstall) to uninstall and find the "install specific version" [here](https://bun.sh/docs/installation#installing).

**Comment by qlaffont** [comment]
I have the same error unfortunatly :/

If you want to test it, I can give you an example : 
```

datasource db {
  provider = "postgresql"
  url      = "postgresql://docker:docker@localhost:5432/project"
}
generator drizzle {
  provider = "prisma-generator-drizzle"

}

model Token {
  id           String @id @unique @default(uuid())
  refreshToken String
  accessToken  String

  owner   User   @relation(fields: [ownerId], references: [id])
  ownerId String

  createdAt DateTime @default(now())
}

model User {
  id            String  @id @unique @default(uuid())

  tokens          Token[]

  createdAt       DateTime         @default(now())
  updatedAt       DateTime         @updatedAt
}
```

**Comment by farreldarian** [comment]
> I have the same error unfortunatly :/ (Bun 1.0.35 / Prisma 5.2.0)
> 
> If you want to test it, I can give you an example :
> 
> ```
> 
> datasource db {
>   provider = "postgresql"
>   url      = "postgresql://docker:docker@localhost:5432/project"
> }
> generator drizzle {
>   provider = "prisma-generator-drizzle"
> 
> }
> 
> model Token {
>   id           String @id @unique @default(uuid())
>   refreshToken String
>   accessToken  String
> 
>   owner   User   @relation(fields: [ownerId], references: [id])
>   ownerId String
> 
>   createdAt DateTime @default(now())
> }
> 
> model User {
>   id            String  @id @unique @default(uuid())
> 
>   tokens          Token[]
> 
>   createdAt       DateTime         @default(now())
>   updatedAt       DateTime         @updatedAt
> }
> ```

Weirdly, I didn't encounter any issues when I ran with this schema.

**Comment by farreldarian** [comment]
@qlaffont @TenviLi It seems that the problem is arising from comments in the tsconfig.json file, as JSON does not support comments by default. I've just released [version 0.6.7](https://www.npmjs.com/package/prisma-generator-drizzle/v/0.6.7) to address this issue. Please give it a try and let me know if it doesn't resolve the issue.

**Comment by qlaffont** [comment]
Nop :/

```
> starter-api@1.0.0 generate /home/quentin/Documents/dev/perso/starter-api
> prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
Expected double-quoted property name in JSON at position 622
```

**Comment by farreldarian** [comment]
> datasource db {
>   provider = "postgresql"
>   url      = "postgresql://docker:docker@localhost:5432/project"
> }
> generator drizzle {
>   provider = "prisma-generator-drizzle"
> 
> }
> 
> model Token {
>   id           String @id @unique @default(uuid())
>   refreshToken String
>   accessToken  String
> 
>   owner   User   @relation(fields: [ownerId], references: [id])
>   ownerId String
> 
>   createdAt DateTime @default(now())
> }
> 
> model User {
>   id            String  @id @unique @default(uuid())
> 
>   tokens          Token[]
> 
>   createdAt       DateTime         @default(now())
>   updatedAt       DateTime         @updatedAt
> }

Do you mind to modify [this repository](https://github.com/farreldarian/repro-generator-error) to reproduce your error?

**Comment by farreldarian** [comment]
> Nop :/
> 
> ```
> > starter-api@1.0.0 generate /home/quentin/Documents/dev/perso/starter-api
> > prisma generate
> 
> Environment variables loaded from .env
> Prisma schema loaded from prisma/schema.prisma
> Error: 
> Expected double-quoted property name in JSON at position 622
> ```

Do you mind to modify [this repository](https://github.com/farreldarian/repro-generator-error) to reproduce your error?

**Comment by qlaffont** [comment]
Strange I don't reproduce the error with deps I have installed...

**Comment by fdarian** [comment]
Feel free to reopen if the issue persists.
